version: '2'
services:
    onssagerparametrizacao-sonar:
        container_name: onssagerparametrizacao-sonar
        image: sonarqube:5.6-alpine
        ports:
            - 9000:9000
            - 9092:9092
